version: 2.1

jobs:
  sleep:
    docker:
      - image: cimg/go:1.20
    resource_class: small
    steps:
      - checkout
      - run:
          name: sleep
          command: echo "sleeping" && sleep 5

workflows:
  sleep:
    jobs:
      - sleep
      - sleep
      - sleep